AWSTemplateFormatVersion: 2010-09-09
Description: This template deploys a CloudWatch Dashboard / Alarms / SNS Topics

Parameters:
  pAlarmAlias:
    Type: String
    MinLength: 1
    MaxLength: 255
    Default: "Dojo-Pythia-userxxx-aplicacionxxx"
  pAlertWrapperTopic:
    Type: String
    MinLength: 1
    MaxLength: 255
    Default: "arn:aws:sns:us-east-1:915725620061:Bco-PagerDutySnsTopic"
  pSNSAppTopicEmail:
    Type: String
    MinLength: 1
    MaxLength: 255
  pSNSDBATopicEmail:
    Type: String
    MinLength: 1
    MaxLength: 255
  pSNSInfraTopicEmail:
    Type: String
    MinLength: 1
    MaxLength: 255
  pbucketName1:
    Type: String
    Description: Bucket Name nu0084001-dcm-monitoreo-poc 
### InstanceId ###
  pInstanceId01:
    Type: String
    Description: Instance ID 


Resources:
######################################################## S3  ################################################
  OpsEventRuleS3:
    Type: AWS::Events::Rule
    Properties:
      Description: S3-DeleteBucket-Alarm
      EventPattern:
        source:
          - aws.s3
        detail-type:
          - AWS API Call via CloudTrail
        detail:
          eventSource:
            - s3.amazonaws.com
          eventName:
            - DeleteBucket
          requestParameters:
            bucketName: [ !Ref pbucketName1 ]
      State: ENABLED

  rOpsEventRuleS3Alarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmActions:
      - Ref: rSNSInfraTopic
      AlarmDescription: !Join [ ": ", [ 'Dojo', !Ref pAlarmAlias, 'A S3 bucket was deleted in account' ]]
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Dimensions:
      - Name: RuleName 
        Value: !Ref OpsEventRuleS3
      EvaluationPeriods: 1
      MetricName: TriggeredRules
      Namespace: AWS/Events
      Period: 60
      Statistic: Maximum
      Threshold: 1
      TreatMissingData: 'notBreaching'

############################################# SNS #########################################
  rSNSInfraTopic:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: !Join [ "-", [ !Ref pAlarmAlias, 'Infra SNS']]
      Subscription:
      - Endpoint: !Ref "pSNSInfraTopicEmail"
        Protocol: email
  rSNSDBATopic:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: !Join [ "-", [ !Ref pAlarmAlias, 'DBA SNS']]
      Subscription:
      - Endpoint: !Ref "pSNSDBATopicEmail"
        Protocol: email
  rSNSAppTopics:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: !Join [ "-", [ !Ref pAlarmAlias, 'App SNS']]
      Subscription:
      - Endpoint: !Ref "pSNSAppTopicEmail"
        Protocol: email


### Alarma CWAgent pInstanceId01
  rIISAlarmsInstanceUserXXX:
    Type: AWS::CloudWatch::Alarm
    Properties:
      Namespace: Dojo-Pythia
      AlarmDescription: !Join [ ": ", [ !Ref pAlarmAlias, 'el proceso IIS se detuvo']]
      MetricName: procstat_lookup pid_count
      Statistic: Average
      Period: 300
      EvaluationPeriods: 1
      ComparisonOperator: LessThanThreshold
      Threshold: 1
      AlarmActions:
      - Ref: rSNSDBATopic
      - Ref: pAlertWrapperTopic
      OKActions:
      - Ref: rSNSDBATopic
      - Ref: pAlertWrapperTopic
      Dimensions:
      - Name: InstanceId
        Value: !Ref pInstanceId01
      - Name: pattern
        Value: C:\Windows\system32\svchost.exe -k iissvcs
      - Name: pid_finder
        Value: native

  rFTPAlarmsInstanceUserXXX:
    Type: AWS::CloudWatch::Alarm
    Properties:
      Namespace: Dojo-Pythia
      AlarmDescription: !Join [ ": ", [ !Ref pAlarmAlias, 'el proceso FTP se detuvo']]
      MetricName: procstat_lookup pid_count
      Statistic: Average
      Period: 300
      EvaluationPeriods: 1
      ComparisonOperator: LessThanThreshold
      Threshold: 1
      AlarmActions:
      - Ref: rSNSDBATopic
      - Ref: pAlertWrapperTopic
      OKActions:
      - Ref: rSNSDBATopic
      - Ref: pAlertWrapperTopic
      Dimensions:
      - Name: InstanceId
        Value: !Ref pInstanceId01
      - Name: pattern
        Value: C:\Windows\system32\svchost.exe -k ftpsvc
      - Name: pid_finder
        Value: native

###################################### Dashboard ##################################
  # rDashboardPdn:
  #   Type: AWS::CloudWatch::Dashboard
  #   Properties:
  #     DashboardName: !Ref pAlarmAlias
  #     DashboardBody: 
  #       Fn::Sub: |
  #                   {

  #                   }

### Alarmas basadas en patrones de errores de SQL nodo 1
## Criticidad Alta 
  # rMFErrorbackupdeviceaw1157001:
  #   Type: AWS::Logs::MetricFilter
  #   Properties: 
  #     FilterPattern: '"ERROR write failure on backup device"'
  #     LogGroupName: Windows_Application
  #     MetricTransformations:
  #       - 
  #         DefaultValue: "0"
  #         MetricValue: "2"
  #         MetricNamespace: "Error_SQL_aw1157001"
  #         MetricName: "mn_Error_backup_device_aw1157001"
  # rAErrorbackupdeviceaw1157001:
  #   Type: AWS::CloudWatch::Alarm
  #   Properties:
  #     Namespace: Error_SQL_aw1157001
  #     AlarmDescription: !Join ["", ["Operating system error 112 - There is not enough space on the disk",!Ref "pAlarmAlias"]]
  #     MetricName: mn_Error_backup_device_aw1157001
  #     Statistic: Maximum
  #     Period: 900
  #     EvaluationPeriods: 1
  #     ComparisonOperator: GreaterThanOrEqualToThreshold
  #     Threshold: 2
  #     AlarmActions:
  #       - Ref: pAlertWrapperTopic
  #     OKActions:
  #       - Ref: pAlertWrapperTopic

